default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.38.0
      hooks:
          - id: commitizen
            stages: [commit-msg]

    - repo: https://github.com/pycqa/isort.git
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: check-ast
          - id: check-json
          - id: mixed-line-ending
          - id: end-of-file-fixer

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.2.3
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-annotations
                - flake8-bandit
                - flake8-commas
                - flake8-docstrings
                - flake8-pyproject
                - flake8-rst-docstrings
                - flake8-use-fstring
                - flake8-walrus

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            additional_dependencies:
                - types-toml
